<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogoMaestroPuebloIndigenasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();
        $categoriaPertenencia = 'pertenencia';
        $categoriaPueblo = 'pueblo';
        $codigoCategoriaPertenencia = 1;
        $codigoCategoriaPueblo = 2;

        $rows = [
            [
                'categoria' => $categoriaPertenencia,
                'codigo' => 1,
                'pueblo' => null,
                'pertenencia_descripcion' => 'Si pertenece a un pueblo indigena u originario',
                'otras_denominaciones' => null,
                'ambito' => null,
                'presencia_departamentos' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPertenencia,
                'codigo' => 2,
                'pueblo' => null,
                'pertenencia_descripcion' => 'Poblacion afroperuana, negra, morena, zamba, mulata, afrodescendiente o parte del pueblo afroperuano',
                'otras_denominaciones' => null,
                'ambito' => null,
                'presencia_departamentos' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPertenencia,
                'codigo' => 3,
                'pueblo' => null,
                'pertenencia_descripcion' => 'No',
                'otras_denominaciones' => null,
                'ambito' => null,
                'presencia_departamentos' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPertenencia,
                'codigo' => 4,
                'pueblo' => null,
                'pertenencia_descripcion' => 'No sabe/no responde',
                'otras_denominaciones' => null,
                'ambito' => null,
                'presencia_departamentos' => null,
                'activo' => true,
            ],

            [
                'categoria' => $categoriaPueblo,
                'codigo' => 1,
                'pueblo' => 'Achuar',
                'otras_denominaciones' => 'Achual, Achuale, Achuare',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 2,
                'pueblo' => 'Aimara',
                'otras_denominaciones' => 'Aru, Aymara',
                'ambito' => 'Andino',
                'presencia_departamentos' => 'Moquegua, Puno, Tacna',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 3,
                'pueblo' => 'Amahuaca',
                'otras_denominaciones' => 'Amunvaka, Yora',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Madre de Dios, Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 4,
                'pueblo' => 'Arabela',
                'otras_denominaciones' => 'Chiripuno, Tapueyocuaca',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 5,
                'pueblo' => 'Ashaninka',
                'otras_denominaciones' => 'Ashaninka',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Ayacucho, Cusco, Huanuco, Junin, Loreto, Madre de Dios, Pasco, Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 6,
                'pueblo' => 'Asheninka',
                'otras_denominaciones' => 'Ashaninka del Gran Pajonal',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto, Pasco, Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 7,
                'pueblo' => 'Awajun',
                'otras_denominaciones' => 'Aents, Aguaruna, Ahuajun',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Amazonas, Cajamarca, Loreto, San Martin, Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 8,
                'pueblo' => 'Bora',
                'otras_denominaciones' => 'Booraa, Boro, Miamuna, Miranha, Miranya, Mirana- Carapana-Tapuyo',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 9,
                'pueblo' => 'Cashinahua',
                'otras_denominaciones' => 'Caxinahua, Huni Kuin, Kachinahua',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 10,
                'pueblo' => 'Chamicuro',
                'otras_denominaciones' => 'Camikodlo, Chamicolos, Chamicura',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 11,
                'pueblo' => 'Chapra',
                'otras_denominaciones' => 'Shapra',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 12,
                'pueblo' => 'Chitonahua',
                'otras_denominaciones' => 'Murunahua, Yora',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 13,
                'pueblo' => 'Ese Eja',
                'otras_denominaciones' => "Ese'ejja, Huarayo, Tiatinagua",
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Madre de Dios',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 14,
                'pueblo' => 'Harakbut',
                'otras_denominaciones' => 'Amarakaeri, Arasaeri, Arasairi, Arazaeri, Huachipaeri, Huachipayri, Kisamberi, Pukirieri, Puncuri, Qachipaeri, Sapiteri, Toioeri, Toyeri, Toyoeri, Tuyuneri, Wachipaeri, Wacipairi',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Cusco, Madre de Dios',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 15,
                'pueblo' => 'Ikitu',
                'otras_denominaciones' => 'Amacacore, Ikito, Iquito, Quiturran',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 16,
                'pueblo' => 'Inapari',
                'otras_denominaciones' => 'Inapari, Inamari, Kushitireni',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Madre de Dios',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 17,
                'pueblo' => 'Iskonawa',
                'otras_denominaciones' => 'Isconahua, Iskobakebo',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 18,
                'pueblo' => 'Jaqaru',
                'otras_denominaciones' => 'Aimara Central, Aimara Tupino, Aru',
                'ambito' => 'Andino',
                'presencia_departamentos' => 'Lima',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 19,
                'pueblo' => 'Jibaro',
                'otras_denominaciones' => 'Chivari, Chiwaro, Jibaro del Rio Corrientes, Siwaro, Shiwiar',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 20,
                'pueblo' => 'Kakataibo',
                'otras_denominaciones' => 'Cashibo-Cacataibo, Uni, Unibo',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Huanuco, Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 21,
                'pueblo' => 'Kakinte',
                'otras_denominaciones' => 'Caquinte, Poyenisati',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Cusco, Junin',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 22,
                'pueblo' => 'Kandozi',
                'otras_denominaciones' => 'Candoshi, Chapara, Chapra, Murato, Shapra',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 23,
                'pueblo' => 'Kapanawa',
                'otras_denominaciones' => 'Buskipani, Capanahua, Nuquencaibo',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 24,
                'pueblo' => 'Kichwa',
                'otras_denominaciones' => 'Inga, Kichwa del Napo, Kichwaruna, Lamas, Llacuash, Quechuas del Pastaza, Quichua, Santarrosinos',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Cusco, Huanuco, Loreto, Madre de Dios, San Martin, Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 25,
                'pueblo' => 'Kukama Kukamiria',
                'otras_denominaciones' => 'Cocama Cocamilla, Ucayali, Xibitaona',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto, Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 26,
                'pueblo' => 'Madija',
                'otras_denominaciones' => 'Culina, Karina, Kolina, Kollina, Kulino, Madiha',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 27,
                'pueblo' => 'Maijuna',
                'otras_denominaciones' => 'Maijiki, Orejon',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 28,
                'pueblo' => 'Marinahua',
                'otras_denominaciones' => 'Onocoin, Yora',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 29,
                'pueblo' => 'Mashco Piro',
                'otras_denominaciones' => 'Mashco, Piro Mashco',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Madre de Dios, Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 30,
                'pueblo' => 'Mastanahua',
                'otras_denominaciones' => 'Matsanahua, Yora',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 31,
                'pueblo' => 'Matses',
                'otras_denominaciones' => 'Mayoruna',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 32,
                'pueblo' => 'Matsigenka',
                'otras_denominaciones' => 'Machiganga, Machigenga, Machiguenga, Matsiganga, Matsiguenga',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Cusco, Madre de Dios, Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 33,
                'pueblo' => 'Muniche',
                'otras_denominaciones' => 'Munichi',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 34,
                'pueblo' => 'Murui-Muinani',
                'otras_denominaciones' => 'Huitoto, Uitoto',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 35,
                'pueblo' => 'Nahua',
                'otras_denominaciones' => 'Yora',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 36,
                'pueblo' => 'Nanti',
                'otras_denominaciones' => 'Matsigenka',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Cusco',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 37,
                'pueblo' => 'Nomatsigenga',
                'otras_denominaciones' => 'Atiri, Nomachiguenga',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Junin',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 38,
                'pueblo' => 'Ocaina',
                'otras_denominaciones' => "Dukaiya, Dyo'xaiya",
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 39,
                'pueblo' => 'Omagua',
                'otras_denominaciones' => 'Ariana, Omagua Yete, Pariana, Unawa',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 40,
                'pueblo' => 'Quechuas',
                'otras_denominaciones' => "Los pueblos Quechuas no tienen otras denominaciones, mas si un conjunto de identidades, entre las que se encuentran: Chopccas, Huancas, Chankas, Huaylas, Q'eros, Canaris, Kana",
                'ambito' => 'Andino',
                'presencia_departamentos' => 'Amazonas, Ancash, Apurimac, Arequipa, Ayacucho, Cajamarca, Cusco, Huancavelica, Huanuco, Ica, Junin, La Libertad, Lambayeque, Lima, Moquegua, Pasco, Puno',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 41,
                'pueblo' => 'Resigaro',
                'otras_denominaciones' => 'Resigero',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 42,
                'pueblo' => 'Secoya',
                'otras_denominaciones' => 'Aido Pai',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 43,
                'pueblo' => 'Sharanahua',
                'otras_denominaciones' => 'Onicoin, Yora',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 44,
                'pueblo' => 'Shawi',
                'otras_denominaciones' => 'Campo-Piyapi, Chayahuita, Chayawita, Shayabit, Tshahui',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto, San Martin',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 45,
                'pueblo' => 'Shipibo-Konibo',
                'otras_denominaciones' => 'Chioeo-Conivo, Joni, Shipibo',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Huanuco, Loreto, Madre de Dios, Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 46,
                'pueblo' => 'Shiwilu',
                'otras_denominaciones' => 'Chebero, Jebero, Shiwila, Xebero',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 47,
                'pueblo' => 'Ticuna',
                'otras_denominaciones' => 'Duuxugu, Tikuna',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 48,
                'pueblo' => 'Urarina',
                'otras_denominaciones' => 'Itucali, Itukale, Kacha Edze',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 49,
                'pueblo' => 'Uro',
                'otras_denominaciones' => 'Uru',
                'ambito' => 'Andino',
                'presencia_departamentos' => 'Puno',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 50,
                'pueblo' => 'Vacacocha',
                'otras_denominaciones' => "A'ewa, Abijira, Abishira, Aushiri, Awshira",
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 51,
                'pueblo' => 'Wampis',
                'otras_denominaciones' => 'Huambiza, Maina, Shuar-Huampis',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Amazonas, Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 52,
                'pueblo' => 'Yagua',
                'otras_denominaciones' => 'Nihamwo, Nihamwo, Yihamwo',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Loreto',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 53,
                'pueblo' => 'Yaminahua',
                'otras_denominaciones' => 'Jjamimawa, Yaminagua, Yora, Yuminahua',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'San Martin, Ucayali',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 54,
                'pueblo' => 'Yanesha',
                'otras_denominaciones' => 'Amage, Amajo, Amuesha, Amuexia, Omage',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Huanuco, Junin, Pasco',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaPueblo,
                'codigo' => 55,
                'pueblo' => 'Yine',
                'otras_denominaciones' => 'Chotaquiro, Pira, Piro, Pirro, Simirinche',
                'ambito' => 'Amazonico',
                'presencia_departamentos' => 'Cusco, Loreto, Madre de Dios, Ucayali',
                'activo' => true,
            ],
        ];

        $rows = array_map(static function (array $row) use (
            $categoriaPertenencia,
            $codigoCategoriaPertenencia,
            $codigoCategoriaPueblo
        ): array {
            $isPertenencia = $row['categoria'] === $categoriaPertenencia;

            return $row + [
                'codigo_categoria' => $isPertenencia ? $codigoCategoriaPertenencia : $codigoCategoriaPueblo,
                'pertenencia_descripcion' => $isPertenencia ? ($row['pertenencia_descripcion'] ?? null) : null,
                'pueblo' => $isPertenencia ? null : $row['pueblo'],
            ];
        }, $rows);

        $rows = array_map(static fn (array $row): array => $row + [
            'created_at' => $now,
            'updated_at' => $now,
        ], $rows);

        DB::table('catalogo_maestro_pueblo_indigenas')->insert($rows);
    }
}
