<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogoMaestroLenguasIndigenasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();
        $categoriaCondicion = 'condicion';
        $categoriaLengua = 'lengua';
        $codigoCategoriaCondicion = 1;
        $codigoCategoriaLengua = 2;

        $rows = [
            [
                'categoria' => $categoriaCondicion,
                'codigo' => 1,
                'lengua' => null,
                'familia_linguistica' => null,
                'ambito' => null,
                'pueblos_que_la_hablan' => null,
                'resolucion_alfabeto' => null,
                'condicion_descripcion' => 'Si',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaCondicion,
                'codigo' => 2,
                'lengua' => null,
                'familia_linguistica' => null,
                'ambito' => null,
                'pueblos_que_la_hablan' => null,
                'resolucion_alfabeto' => null,
                'condicion_descripcion' => 'No',
                'activo' => true,
            ],
            [
                'categoria' => $categoriaCondicion,
                'codigo' => 3,
                'lengua' => null,
                'familia_linguistica' => null,
                'ambito' => null,
                'pueblos_que_la_hablan' => null,
                'resolucion_alfabeto' => null,
                'condicion_descripcion' => 'No sabe/no responde',
                'activo' => true,
            ],

            [
                'categoria' => $categoriaLengua,
                'codigo' => 1,
                'lengua' => 'Achuar',
                'familia_linguistica' => 'Jibaro',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Achuar, Jibaro',
                'resolucion_alfabeto' => 'R.M. 487-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 2,
                'lengua' => 'Aimara',
                'familia_linguistica' => 'Aru',
                'ambito' => 'Andino',
                'pueblos_que_la_hablan' => 'Aimara',
                'resolucion_alfabeto' => 'R.M. 1218-85-ED',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 3,
                'lengua' => 'Amahuaca',
                'familia_linguistica' => 'Pano',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Amahuaca',
                'resolucion_alfabeto' => 'R.M. 064-2017-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 4,
                'lengua' => 'Arabela',
                'familia_linguistica' => 'Zaparo',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Arabela',
                'resolucion_alfabeto' => 'R.M. 434-2016-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 5,
                'lengua' => 'Ashaninka',
                'familia_linguistica' => 'Arawak',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Ashaninka',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 6,
                'lengua' => 'Asheninka',
                'familia_linguistica' => 'Arawak',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Asheninka',
                'resolucion_alfabeto' => 'R.M. 199-2019-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 7,
                'lengua' => 'Awajun',
                'familia_linguistica' => 'Jibaro',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Awajun',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 8,
                'lengua' => 'Bora',
                'familia_linguistica' => 'Bora',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Bora',
                'resolucion_alfabeto' => 'R.M. 512-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 9,
                'lengua' => 'Cashinahua',
                'familia_linguistica' => 'Pano',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Cashinahua',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 10,
                'lengua' => 'Chamikuro',
                'familia_linguistica' => 'Arawak',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Chamicuro',
                'resolucion_alfabeto' => 'R.M. 212-2020-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 11,
                'lengua' => 'Ese Eja',
                'familia_linguistica' => 'Tacana',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Ese Eja',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 12,
                'lengua' => 'Harakbut',
                'familia_linguistica' => 'Harakbut',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Harakbut',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 13,
                'lengua' => 'Ikitu',
                'familia_linguistica' => 'Zaparo',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Ikitu',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 14,
                'lengua' => 'Inapari',
                'familia_linguistica' => 'Arawak',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Inapari',
                'resolucion_alfabeto' => 'R.M. 542-2019-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 15,
                'lengua' => 'Iskonawa',
                'familia_linguistica' => 'Pano',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Iskonawa',
                'resolucion_alfabeto' => 'R.M. 163-2018-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 16,
                'lengua' => 'Jaqaru',
                'familia_linguistica' => 'Aru',
                'ambito' => 'Andino',
                'pueblos_que_la_hablan' => 'Jaqaru',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 17,
                'lengua' => 'Kakataibo',
                'familia_linguistica' => 'Pano',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Kakataibo',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 18,
                'lengua' => 'Kakinte',
                'familia_linguistica' => 'Arawak',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Kakinte',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 19,
                'lengua' => 'Kandozi-Chapra',
                'familia_linguistica' => 'Kandozi',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Chapra, Kandozi',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 20,
                'lengua' => 'Kapanawa',
                'familia_linguistica' => 'Pano',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Kapanawa',
                'resolucion_alfabeto' => 'R.M. 009-2016-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 21,
                'lengua' => 'Kawki',
                'familia_linguistica' => 'Aru',
                'ambito' => 'Andino',
                'pueblos_que_la_hablan' => '-*',
                'resolucion_alfabeto' => 'R.M. 106-2017-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 22,
                'lengua' => 'Kukama Kukamiria',
                'familia_linguistica' => 'Tupi-guarani',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Kukama Kukamiria',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 23,
                'lengua' => 'Madija',
                'familia_linguistica' => 'Arawa',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Madija',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 24,
                'lengua' => 'Maijiki',
                'familia_linguistica' => 'Tucano',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Maijuna',
                'resolucion_alfabeto' => 'R.M. 521-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 25,
                'lengua' => 'Matses',
                'familia_linguistica' => 'Pano',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Matses',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 26,
                'lengua' => 'Matsigenka',
                'familia_linguistica' => 'Arawak',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Matsigenka',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 27,
                'lengua' => 'Matsigenka Montetokunirira',
                'familia_linguistica' => 'Arawak',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Nanti',
                'resolucion_alfabeto' => 'R.M. 706-2018-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 28,
                'lengua' => 'Munichi',
                'familia_linguistica' => 'Muniche',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Muniche',
                'resolucion_alfabeto' => 'R.M. 111-2020-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 29,
                'lengua' => 'Murui-Muinani',
                'familia_linguistica' => 'Huitoto',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Murui-Muinani',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 30,
                'lengua' => 'Nahua',
                'familia_linguistica' => 'Pano',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Nahua',
                'resolucion_alfabeto' => 'R.M. 139-2018-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 31,
                'lengua' => 'Nomatsigenga',
                'familia_linguistica' => 'Arawak',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Nomatsigenga',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 32,
                'lengua' => 'Ocaina',
                'familia_linguistica' => 'Huitoto',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Ocaina',
                'resolucion_alfabeto' => 'R.M. 040-2017-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 33,
                'lengua' => 'Omagua',
                'familia_linguistica' => 'Tupi-guarani',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Omagua',
                'resolucion_alfabeto' => 'R.M. 112-2020-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 34,
                'lengua' => 'Quechua',
                'familia_linguistica' => 'Quechua',
                'ambito' => 'Andino / Amazonico',
                'pueblos_que_la_hablan' => 'Kichwa, Quechuas',
                'resolucion_alfabeto' => 'R.M. 1218-85-ED',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 35,
                'lengua' => 'Resigaro',
                'familia_linguistica' => 'Arawak',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Resigaro',
                'resolucion_alfabeto' => 'R.M. 210-2020-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 36,
                'lengua' => 'Secoya',
                'familia_linguistica' => 'Tucano',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Secoya',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 37,
                'lengua' => 'Sharanahua',
                'familia_linguistica' => 'Pano',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Marinahua, Mastanahua, Sharanahua',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 38,
                'lengua' => 'Shawi',
                'familia_linguistica' => 'Cahuapana',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Shawi',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 39,
                'lengua' => 'Shipibo-Konibo',
                'familia_linguistica' => 'Pano',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Shipibo-Konibo',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 40,
                'lengua' => 'Shiwilu',
                'familia_linguistica' => 'Cahuapana',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Shiwilu',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 41,
                'lengua' => 'Taushiro',
                'familia_linguistica' => 'Zaparo',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => '-*',
                'resolucion_alfabeto' => 'R.M. 110-2020-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 42,
                'lengua' => 'Ticuna',
                'familia_linguistica' => 'Ticuna',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Ticuna',
                'resolucion_alfabeto' => 'R.M. 730-2017-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 43,
                'lengua' => 'Urarina',
                'familia_linguistica' => 'Shimaco',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Urarina',
                'resolucion_alfabeto' => 'R.M. 095-2016-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 44,
                'lengua' => 'Wampis',
                'familia_linguistica' => 'Jibaro',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Wampis',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 45,
                'lengua' => 'Yagua',
                'familia_linguistica' => 'Peba-yagua',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Yagua',
                'resolucion_alfabeto' => 'R.M. 536-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 46,
                'lengua' => 'Yaminahua',
                'familia_linguistica' => 'Pano',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Chitonahua, Yaminahua',
                'resolucion_alfabeto' => 'R.M. 138-2017-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 47,
                'lengua' => 'Yanesha',
                'familia_linguistica' => 'Arawak',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Yanesha',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
            [
                'categoria' => $categoriaLengua,
                'codigo' => 48,
                'lengua' => 'Yine',
                'familia_linguistica' => 'Arawak',
                'ambito' => 'Amazonico',
                'pueblos_que_la_hablan' => 'Mashco Piro, Yine',
                'resolucion_alfabeto' => 'R.M. 303-2015-MINEDU',
                'condicion_descripcion' => null,
                'activo' => true,
            ],
        ];

        $rows = array_map(static function (array $row) use (
            $categoriaCondicion,
            $codigoCategoriaCondicion,
            $codigoCategoriaLengua
        ): array {
            $isCondicion = $row['categoria'] === $categoriaCondicion;

            return $row + [
                'codigo_categoria' => $isCondicion ? $codigoCategoriaCondicion : $codigoCategoriaLengua,
                'condicion_descripcion' => $isCondicion ? ($row['condicion_descripcion'] ?? null) : null,
                'lengua' => $isCondicion ? null : $row['lengua'],
            ];
        }, $rows);

        $rows = array_map(static fn (array $row): array => $row + [
            'created_at' => $now,
            'updated_at' => $now,
        ], $rows);

        DB::table('catalogo_maestro_lenguas_indigenas')->insert($rows);
    }
}
