<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaestroNacionalidadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $rows = [
            ['codigo' => 1, 'descripcion' => 'AFGANA', 'activo' => true],
            ['codigo' => 2, 'descripcion' => 'ALBANESA', 'activo' => true],
            ['codigo' => 3, 'descripcion' => 'ALEMANA', 'activo' => true],
            ['codigo' => 4, 'descripcion' => 'ANDORRANA', 'activo' => true],
            ['codigo' => 5, 'descripcion' => 'ANGOLENA', 'activo' => true],
            ['codigo' => 6, 'descripcion' => 'ANTIGUANA', 'activo' => true],
            ['codigo' => 8, 'descripcion' => 'ARGELINA', 'activo' => true],
            ['codigo' => 9, 'descripcion' => 'ARGENTINA', 'activo' => true],
            ['codigo' => 10, 'descripcion' => 'ARMENIA', 'activo' => true],
            ['codigo' => 11, 'descripcion' => 'ARUBENA', 'activo' => true],
            ['codigo' => 12, 'descripcion' => 'AUSTRALIANA', 'activo' => true],
            ['codigo' => 13, 'descripcion' => 'AUSTRIACA', 'activo' => true],
            ['codigo' => 14, 'descripcion' => 'AZERBAIYANA', 'activo' => true],
            ['codigo' => 15, 'descripcion' => 'BAHAMENA', 'activo' => true],
            ['codigo' => 16, 'descripcion' => 'BANGLADESI', 'activo' => true],
            ['codigo' => 17, 'descripcion' => 'BARBADENSE', 'activo' => true],
            ['codigo' => 18, 'descripcion' => 'BAREINI', 'activo' => true],
            ['codigo' => 19, 'descripcion' => 'BELGA', 'activo' => true],
            ['codigo' => 20, 'descripcion' => 'BELICENA', 'activo' => true],
            ['codigo' => 21, 'descripcion' => 'BENINESA', 'activo' => true],
            ['codigo' => 22, 'descripcion' => 'BIELORRUSA', 'activo' => true],
            ['codigo' => 23, 'descripcion' => 'BIRMANA', 'activo' => true],
            ['codigo' => 24, 'descripcion' => 'BOLIVIANA', 'activo' => true],
            ['codigo' => 25, 'descripcion' => 'BOSNIA', 'activo' => true],
            ['codigo' => 26, 'descripcion' => 'BOTSUANA', 'activo' => true],
            ['codigo' => 27, 'descripcion' => 'BRASILENA', 'activo' => true],
            ['codigo' => 149, 'descripcion' => 'BRITANICA', 'activo' => true],
            ['codigo' => 28, 'descripcion' => 'BRUNEANA', 'activo' => true],
            ['codigo' => 29, 'descripcion' => 'BULGARA', 'activo' => true],
            ['codigo' => 30, 'descripcion' => 'BURKINES', 'activo' => true],
            ['codigo' => 31, 'descripcion' => 'BURUNDESA', 'activo' => true],
            ['codigo' => 32, 'descripcion' => 'BUTANESA', 'activo' => true],
            ['codigo' => 33, 'descripcion' => 'CABOVERDIANA', 'activo' => true],
            ['codigo' => 34, 'descripcion' => 'CAMBOYANA', 'activo' => true],
            ['codigo' => 35, 'descripcion' => 'CAMERUNESA', 'activo' => true],
            ['codigo' => 36, 'descripcion' => 'CANADIENSE', 'activo' => true],
            ['codigo' => 37, 'descripcion' => 'CATARI', 'activo' => true],
            ['codigo' => 173, 'descripcion' => 'CEILANESA', 'activo' => true],
            ['codigo' => 150, 'descripcion' => 'CENTROAFRICANA', 'activo' => true],
            ['codigo' => 38, 'descripcion' => 'CHADIANA', 'activo' => true],
            ['codigo' => 151, 'descripcion' => 'CHECA', 'activo' => true],
            ['codigo' => 39, 'descripcion' => 'CHILENA', 'activo' => true],
            ['codigo' => 40, 'descripcion' => 'CHINA', 'activo' => true],
            ['codigo' => 41, 'descripcion' => 'CHIPRIOTA', 'activo' => true],
            ['codigo' => 43, 'descripcion' => 'COLOMBIANA', 'activo' => true],
            ['codigo' => 44, 'descripcion' => 'COMORENSE', 'activo' => true],
            ['codigo' => 153, 'descripcion' => 'CONGOLENA', 'activo' => true],
            ['codigo' => 154, 'descripcion' => 'CONGOLENA', 'activo' => true],
            ['codigo' => 90, 'descripcion' => 'COOKIANA', 'activo' => true],
            ['codigo' => 48, 'descripcion' => 'COSTARRICENSE', 'activo' => true],
            ['codigo' => 161, 'descripcion' => 'CRISTOBALENA', 'activo' => true],
            ['codigo' => 49, 'descripcion' => 'CROATA', 'activo' => true],
            ['codigo' => 50, 'descripcion' => 'CUBANA', 'activo' => true],
            ['codigo' => 51, 'descripcion' => 'DANESA', 'activo' => true],
            ['codigo' => 155, 'descripcion' => 'DOMINICANA', 'activo' => true],
            ['codigo' => 52, 'descripcion' => 'DOMINIQUES', 'activo' => true],
            ['codigo' => 77, 'descripcion' => 'ECUATOGUINEANA', 'activo' => true],
            ['codigo' => 53, 'descripcion' => 'ECUATORIANA', 'activo' => true],
            ['codigo' => 54, 'descripcion' => 'EGIPCIA', 'activo' => true],
            ['codigo' => 56, 'descripcion' => 'EMIRATI', 'activo' => true],
            ['codigo' => 57, 'descripcion' => 'ERITREA', 'activo' => true],
            ['codigo' => 58, 'descripcion' => 'ESLOVACA', 'activo' => true],
            ['codigo' => 59, 'descripcion' => 'ESLOVENA', 'activo' => true],
            ['codigo' => 60, 'descripcion' => 'ESPANOLA', 'activo' => true],
            ['codigo' => 61, 'descripcion' => 'ESTADOUNIDENSE', 'activo' => true],
            ['codigo' => 62, 'descripcion' => 'ESTONIA', 'activo' => true],
            ['codigo' => 63, 'descripcion' => 'ETIOPE', 'activo' => true],
            ['codigo' => 64, 'descripcion' => 'FILIPINA', 'activo' => true],
            ['codigo' => 65, 'descripcion' => 'FINLANDESA', 'activo' => true],
            ['codigo' => 66, 'descripcion' => 'FIYIANA', 'activo' => true],
            ['codigo' => 67, 'descripcion' => 'FRANCESA', 'activo' => true],
            ['codigo' => 68, 'descripcion' => 'GABONESA', 'activo' => true],
            ['codigo' => 69, 'descripcion' => 'GAMBIANA', 'activo' => true],
            ['codigo' => 70, 'descripcion' => 'GEORGIANA', 'activo' => true],
            ['codigo' => 72, 'descripcion' => 'GHANESA', 'activo' => true],
            ['codigo' => 71, 'descripcion' => 'GIBRALTARENA', 'activo' => true],
            ['codigo' => 73, 'descripcion' => 'GRANADINA', 'activo' => true],
            ['codigo' => 74, 'descripcion' => 'GRIEGA', 'activo' => true],
            ['codigo' => 75, 'descripcion' => 'GROENLANDESA', 'activo' => true],
            ['codigo' => 76, 'descripcion' => 'GUATEMALTECA', 'activo' => true],
            ['codigo' => 78, 'descripcion' => 'GUINEANA', 'activo' => true],
            ['codigo' => 79, 'descripcion' => 'GUINEANA', 'activo' => true],
            ['codigo' => 80, 'descripcion' => 'GUYANESA', 'activo' => true],
            ['codigo' => 81, 'descripcion' => 'HAITIANA', 'activo' => true],
            ['codigo' => 84, 'descripcion' => 'HINDU', 'activo' => true],
            ['codigo' => 82, 'descripcion' => 'HONDURENA', 'activo' => true],
            ['codigo' => 83, 'descripcion' => 'HUNGARA', 'activo' => true],
            ['codigo' => 145, 'descripcion' => 'INDONESIA', 'activo' => true],
            ['codigo' => 87, 'descripcion' => 'IRANI', 'activo' => true],
            ['codigo' => 86, 'descripcion' => 'IRAQUI', 'activo' => true],
            ['codigo' => 88, 'descripcion' => 'IRLANDESA', 'activo' => true],
            ['codigo' => 89, 'descripcion' => 'ISLANDESA', 'activo' => true],
            ['codigo' => 93, 'descripcion' => 'ISRAELI', 'activo' => true],
            ['codigo' => 94, 'descripcion' => 'ITALIANA', 'activo' => true],
            ['codigo' => 95, 'descripcion' => 'JAMAIQUINA', 'activo' => true],
            ['codigo' => 96, 'descripcion' => 'JAPONESA', 'activo' => true],
            ['codigo' => 97, 'descripcion' => 'JORDANA', 'activo' => true],
            ['codigo' => 98, 'descripcion' => 'KAZAJA', 'activo' => true],
            ['codigo' => 99, 'descripcion' => 'KENIATA', 'activo' => true],
            ['codigo' => 100, 'descripcion' => 'KIRGUISA', 'activo' => true],
            ['codigo' => 101, 'descripcion' => 'KIRIBATIANA', 'activo' => true],
            ['codigo' => 102, 'descripcion' => 'KUWAITI', 'activo' => true],
            ['codigo' => 103, 'descripcion' => 'LAOSIANA', 'activo' => true],
            ['codigo' => 104, 'descripcion' => 'LESOTENSE', 'activo' => true],
            ['codigo' => 105, 'descripcion' => 'LETONA', 'activo' => true],
            ['codigo' => 106, 'descripcion' => 'LIBANESA', 'activo' => true],
            ['codigo' => 107, 'descripcion' => 'LIBERIANA', 'activo' => true],
            ['codigo' => 108, 'descripcion' => 'LIBIA', 'activo' => true],
            ['codigo' => 109, 'descripcion' => 'LIECHTENSTEINIANA', 'activo' => true],
            ['codigo' => 110, 'descripcion' => 'LITUANA', 'activo' => true],
            ['codigo' => 111, 'descripcion' => 'LUXEMBURGUESA', 'activo' => true],
            ['codigo' => 152, 'descripcion' => 'MACEDONIA', 'activo' => true],
            ['codigo' => 113, 'descripcion' => 'MALASIA', 'activo' => true],
            ['codigo' => 114, 'descripcion' => 'MALAUI', 'activo' => true],
            ['codigo' => 115, 'descripcion' => 'MALDIVA', 'activo' => true],
            ['codigo' => 112, 'descripcion' => 'MALGACHE', 'activo' => true],
            ['codigo' => 116, 'descripcion' => 'MALIENSE', 'activo' => true],
            ['codigo' => 117, 'descripcion' => 'MALTESA', 'activo' => true],
            ['codigo' => 47, 'descripcion' => 'MARFILENA', 'activo' => true],
            ['codigo' => 118, 'descripcion' => 'MARROQUI', 'activo' => true],
            ['codigo' => 91, 'descripcion' => 'MARSHALESA', 'activo' => true],
            ['codigo' => 119, 'descripcion' => 'MARTINIQUES', 'activo' => true],
            ['codigo' => 120, 'descripcion' => 'MAURICIANA', 'activo' => true],
            ['codigo' => 121, 'descripcion' => 'MAURITANA', 'activo' => true],
            ['codigo' => 122, 'descripcion' => 'MEXICANA', 'activo' => true],
            ['codigo' => 123, 'descripcion' => 'MICRONESIA', 'activo' => true],
            ['codigo' => 124, 'descripcion' => 'MOLDAVA', 'activo' => true],
            ['codigo' => 125, 'descripcion' => 'MONEGASCA', 'activo' => true],
            ['codigo' => 126, 'descripcion' => 'MONGOLA', 'activo' => true],
            ['codigo' => 127, 'descripcion' => 'MONTENEGRINA', 'activo' => true],
            ['codigo' => 128, 'descripcion' => 'MOZAMBIQUENA', 'activo' => true],
            ['codigo' => 129, 'descripcion' => 'NAMIBIA', 'activo' => true],
            ['codigo' => 130, 'descripcion' => 'NAURUANA', 'activo' => true],
            ['codigo' => 138, 'descripcion' => 'NEERLANDESA', 'activo' => true],
            ['codigo' => 136, 'descripcion' => 'NEOZELANDESA', 'activo' => true],
            ['codigo' => 131, 'descripcion' => 'NEPALI', 'activo' => true],
            ['codigo' => 132, 'descripcion' => 'NICARAGUENSE', 'activo' => true],
            ['codigo' => 134, 'descripcion' => 'NIGERIANA', 'activo' => true],
            ['codigo' => 133, 'descripcion' => 'NIGERINA', 'activo' => true],
            ['codigo' => 45, 'descripcion' => 'NORCOREANA', 'activo' => true],
            ['codigo' => 135, 'descripcion' => 'NORUEGA', 'activo' => true],
            ['codigo' => 137, 'descripcion' => 'OMANI', 'activo' => true],
            ['codigo' => 139, 'descripcion' => 'PAKISTANI', 'activo' => true],
            ['codigo' => 140, 'descripcion' => 'PALAUANA', 'activo' => true],
            ['codigo' => 141, 'descripcion' => 'PALESTINA', 'activo' => true],
            ['codigo' => 142, 'descripcion' => 'PANAMENA', 'activo' => true],
            ['codigo' => 143, 'descripcion' => 'PAPU', 'activo' => true],
            ['codigo' => 144, 'descripcion' => 'PARAGUAYA', 'activo' => true],
            ['codigo' => 85, 'descripcion' => 'PERUANA', 'activo' => true],
            ['codigo' => 146, 'descripcion' => 'POLACA', 'activo' => true],
            ['codigo' => 147, 'descripcion' => 'PORTUGUESA', 'activo' => true],
            ['codigo' => 148, 'descripcion' => 'PUERTORRIQUENA', 'activo' => true],
            ['codigo' => 157, 'descripcion' => 'RUANDESA', 'activo' => true],
            ['codigo' => 158, 'descripcion' => 'RUMANA', 'activo' => true],
            ['codigo' => 159, 'descripcion' => 'RUSA', 'activo' => true],
            ['codigo' => 92, 'descripcion' => 'SALOMONENSE', 'activo' => true],
            ['codigo' => 55, 'descripcion' => 'SALVADORENA', 'activo' => true],
            ['codigo' => 160, 'descripcion' => 'SAMOANA', 'activo' => true],
            ['codigo' => 162, 'descripcion' => 'SANMARINENSE', 'activo' => true],
            ['codigo' => 164, 'descripcion' => 'SANTALUCENSE', 'activo' => true],
            ['codigo' => 165, 'descripcion' => 'SANTOTOMENSE', 'activo' => true],
            ['codigo' => 163, 'descripcion' => 'SANVICENTINA', 'activo' => true],
            ['codigo' => 7, 'descripcion' => 'SAUDI', 'activo' => true],
            ['codigo' => 166, 'descripcion' => 'SENEGALESA', 'activo' => true],
            ['codigo' => 167, 'descripcion' => 'SERBIA', 'activo' => true],
            ['codigo' => 168, 'descripcion' => 'SEYCHELLENSE', 'activo' => true],
            ['codigo' => 169, 'descripcion' => 'SIERRALEONESA', 'activo' => true],
            ['codigo' => 170, 'descripcion' => 'SINGAPURENSE', 'activo' => true],
            ['codigo' => 171, 'descripcion' => 'SIRIA', 'activo' => true],
            ['codigo' => 172, 'descripcion' => 'SOMALI', 'activo' => true],
            ['codigo' => 174, 'descripcion' => 'SUAZI', 'activo' => true],
            ['codigo' => 156, 'descripcion' => 'SUDAFRICANA', 'activo' => true],
            ['codigo' => 176, 'descripcion' => 'SUDANESA', 'activo' => true],
            ['codigo' => 177, 'descripcion' => 'SUECA', 'activo' => true],
            ['codigo' => 178, 'descripcion' => 'SUIZA', 'activo' => true],
            ['codigo' => 46, 'descripcion' => 'SURCOREANA', 'activo' => true],
            ['codigo' => 179, 'descripcion' => 'SURINAMESA', 'activo' => true],
            ['codigo' => 175, 'descripcion' => 'SURSUDANESA', 'activo' => true],
            ['codigo' => 180, 'descripcion' => 'TAILANDESA', 'activo' => true],
            ['codigo' => 202, 'descripcion' => 'TAIWANES', 'activo' => true],
            ['codigo' => 181, 'descripcion' => 'TANZANA', 'activo' => true],
            ['codigo' => 182, 'descripcion' => 'TAYIKA', 'activo' => true],
            ['codigo' => 183, 'descripcion' => 'TIMORENSE', 'activo' => true],
            ['codigo' => 184, 'descripcion' => 'TOGOLESA', 'activo' => true],
            ['codigo' => 185, 'descripcion' => 'TONGANA', 'activo' => true],
            ['codigo' => 186, 'descripcion' => 'TRINITENSE', 'activo' => true],
            ['codigo' => 187, 'descripcion' => 'TUNECINA', 'activo' => true],
            ['codigo' => 189, 'descripcion' => 'TURCA', 'activo' => true],
            ['codigo' => 188, 'descripcion' => 'TURCOMANA', 'activo' => true],
            ['codigo' => 190, 'descripcion' => 'TUVALUANA', 'activo' => true],
            ['codigo' => 191, 'descripcion' => 'UCRANIANA', 'activo' => true],
            ['codigo' => 192, 'descripcion' => 'UGANDESA', 'activo' => true],
            ['codigo' => 193, 'descripcion' => 'URUGUAYA', 'activo' => true],
            ['codigo' => 194, 'descripcion' => 'UZBEKA', 'activo' => true],
            ['codigo' => 195, 'descripcion' => 'VANUATUENSE', 'activo' => true],
            ['codigo' => 42, 'descripcion' => 'VATICANA', 'activo' => true],
            ['codigo' => 196, 'descripcion' => 'VENEZOLANA', 'activo' => true],
            ['codigo' => 197, 'descripcion' => 'VIETNAMITA', 'activo' => true],
            ['codigo' => 198, 'descripcion' => 'YEMENI', 'activo' => true],
            ['codigo' => 199, 'descripcion' => 'YIBUTIANA', 'activo' => true],
            ['codigo' => 200, 'descripcion' => 'ZAMBIANA', 'activo' => true],
            ['codigo' => 201, 'descripcion' => 'ZIMBABUENSE', 'activo' => true],
        ];

        $rows = array_map(static fn (array $row): array => $row + [
            'created_at' => $now,
            'updated_at' => $now,
        ], $rows);

        DB::table('maestro_nacionalidad')->insert($rows);
    }
}
