<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaestroPaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $rows = [
            ['codigo' => 9327, 'descripcion' => 'Afganistan', 'activo' => true],
            ['codigo' => 9443, 'descripcion' => 'Albania', 'activo' => true],
            ['codigo' => 9402, 'descripcion' => 'Alemania', 'activo' => true],
            ['codigo' => 9401, 'descripcion' => 'Alemania Republica Democratica', 'activo' => true],
            ['codigo' => 9442, 'descripcion' => 'Andorra, Principado De', 'activo' => true],
            ['codigo' => 9113, 'descripcion' => 'Angola', 'activo' => true],
            ['codigo' => 9237, 'descripcion' => 'Antigua Y Barbuda', 'activo' => true],
            ['codigo' => 9201, 'descripcion' => 'Antillas Holandesas', 'activo' => true],
            ['codigo' => 9319, 'descripcion' => 'Arabia Saudita', 'activo' => true],
            ['codigo' => 9101, 'descripcion' => 'Argelia', 'activo' => true],
            ['codigo' => 9202, 'descripcion' => 'Argentina', 'activo' => true],
            ['codigo' => 9501, 'descripcion' => 'Australia', 'activo' => true],
            ['codigo' => 9403, 'descripcion' => 'Austria', 'activo' => true],
            ['codigo' => 9446, 'descripcion' => 'Azerbaiyan', 'activo' => true],
            ['codigo' => 9203, 'descripcion' => 'Bahamas, Islas', 'activo' => true],
            ['codigo' => 9334, 'descripcion' => 'Bangladesh', 'activo' => true],
            ['codigo' => 9229, 'descripcion' => 'Barbados', 'activo' => true],
            ['codigo' => 9341, 'descripcion' => 'Barein', 'activo' => true],
            ['codigo' => 9404, 'descripcion' => 'Belgica', 'activo' => true],
            ['codigo' => 9232, 'descripcion' => 'Belice', 'activo' => true],
            ['codigo' => 9436, 'descripcion' => 'Bielorrusia', 'activo' => true],
            ['codigo' => 9340, 'descripcion' => 'Birmania', 'activo' => true],
            ['codigo' => 9204, 'descripcion' => 'Bolivia', 'activo' => true],
            ['codigo' => 9445, 'descripcion' => 'Bosnia Y Herzegovina', 'activo' => true],
            ['codigo' => 9130, 'descripcion' => 'Botsuana', 'activo' => true],
            ['codigo' => 9205, 'descripcion' => 'Brasil', 'activo' => true],
            ['codigo' => 9345, 'descripcion' => 'Brunei', 'activo' => true],
            ['codigo' => 9405, 'descripcion' => 'Bulgaria', 'activo' => true],
            ['codigo' => 9114, 'descripcion' => 'Burkina Faso', 'activo' => true],
            ['codigo' => 9333, 'descripcion' => 'Camboya', 'activo' => true],
            ['codigo' => 9123, 'descripcion' => 'Camerun', 'activo' => true],
            ['codigo' => 9206, 'descripcion' => 'Canada', 'activo' => true],
            ['codigo' => 9241, 'descripcion' => 'Caribe Neerlandes', 'activo' => true],
            ['codigo' => 9338, 'descripcion' => 'Catar', 'activo' => true],
            ['codigo' => 9210, 'descripcion' => 'Chile', 'activo' => true],
            ['codigo' => 9302, 'descripcion' => 'China, Republica Popular', 'activo' => true],
            ['codigo' => 9407, 'descripcion' => 'Chipre', 'activo' => true],
            ['codigo' => 9207, 'descripcion' => 'Colombia', 'activo' => true],
            ['codigo' => 9316, 'descripcion' => 'Corea Del Norte', 'activo' => true],
            ['codigo' => 9102, 'descripcion' => 'Costa De Marfil', 'activo' => true],
            ['codigo' => 9208, 'descripcion' => 'Costa Rica', 'activo' => true],
            ['codigo' => 9431, 'descripcion' => 'Croacia', 'activo' => true],
            ['codigo' => 9209, 'descripcion' => 'Cuba', 'activo' => true],
            ['codigo' => 9408, 'descripcion' => 'Dinamarca', 'activo' => true],
            ['codigo' => 9234, 'descripcion' => 'Dominica', 'activo' => true],
            ['codigo' => 9211, 'descripcion' => 'Ecuador', 'activo' => true],
            ['codigo' => 9212, 'descripcion' => 'El Salvador', 'activo' => true],
            ['codigo' => 9337, 'descripcion' => 'Emiratos Arabes Unidos', 'activo' => true],
            ['codigo' => 9438, 'descripcion' => 'Eslovaquia', 'activo' => true],
            ['codigo' => 9433, 'descripcion' => 'Eslovenia', 'activo' => true],
            ['codigo' => 9409, 'descripcion' => 'Espana', 'activo' => true],
            ['codigo' => 9213, 'descripcion' => 'Estados Unidos De America', 'activo' => true],
            ['codigo' => 9444, 'descripcion' => 'Estonia', 'activo' => true],
            ['codigo' => 9120, 'descripcion' => 'Etiopia', 'activo' => true],
            ['codigo' => 9332, 'descripcion' => 'Filipinas', 'activo' => true],
            ['codigo' => 9410, 'descripcion' => 'Finlandia', 'activo' => true],
            ['codigo' => 9411, 'descripcion' => 'Francia', 'activo' => true],
            ['codigo' => 9131, 'descripcion' => 'Gabon', 'activo' => true],
            ['codigo' => 9331, 'descripcion' => 'Georgia', 'activo' => true],
            ['codigo' => 9112, 'descripcion' => 'Ghana', 'activo' => true],
            ['codigo' => 9240, 'descripcion' => 'Granada', 'activo' => true],
            ['codigo' => 9413, 'descripcion' => 'Grecia', 'activo' => true],
            ['codigo' => 9215, 'descripcion' => 'Guatemala', 'activo' => true],
            ['codigo' => 9230, 'descripcion' => 'Guayana Francesa', 'activo' => true],
            ['codigo' => 9122, 'descripcion' => 'Guinea Ecuatorial', 'activo' => true],
            ['codigo' => 9231, 'descripcion' => 'Guyana', 'activo' => true],
            ['codigo' => 9216, 'descripcion' => 'Haiti', 'activo' => true],
            ['codigo' => 9217, 'descripcion' => 'Honduras', 'activo' => true],
            ['codigo' => 9303, 'descripcion' => 'Hong Kong (Colonia Britanica)', 'activo' => true],
            ['codigo' => 9415, 'descripcion' => 'Hungria', 'activo' => true],
            ['codigo' => 9304, 'descripcion' => 'India', 'activo' => true],
            ['codigo' => 9311, 'descripcion' => 'Indonesia', 'activo' => true],
            ['codigo' => 9305, 'descripcion' => 'Irak', 'activo' => true],
            ['codigo' => 9324, 'descripcion' => 'Iran', 'activo' => true],
            ['codigo' => 9418, 'descripcion' => 'Irlanda', 'activo' => true],
            ['codigo' => 9441, 'descripcion' => 'Irlanda Del Norte', 'activo' => true],
            ['codigo' => 9453, 'descripcion' => 'Isla De Jersey', 'activo' => true],
            ['codigo' => 9416, 'descripcion' => 'Islandia', 'activo' => true],
            ['codigo' => 9238, 'descripcion' => 'Islas Bermudas', 'activo' => true],
            ['codigo' => 9236, 'descripcion' => 'Islas Caiman', 'activo' => true],
            ['codigo' => 9306, 'descripcion' => 'Israel', 'activo' => true],
            ['codigo' => 9417, 'descripcion' => 'Italia', 'activo' => true],
            ['codigo' => 9218, 'descripcion' => 'Jamaica', 'activo' => true],
            ['codigo' => 9307, 'descripcion' => 'Japon', 'activo' => true],
            ['codigo' => 9313, 'descripcion' => 'Jordania', 'activo' => true],
            ['codigo' => 9321, 'descripcion' => 'Kazajstan', 'activo' => true],
            ['codigo' => 9104, 'descripcion' => 'Kenia', 'activo' => true],
            ['codigo' => 9326, 'descripcion' => 'Kirguistan', 'activo' => true],
            ['codigo' => 9328, 'descripcion' => 'Kuwait', 'activo' => true],
            ['codigo' => 9439, 'descripcion' => 'Letonia', 'activo' => true],
            ['codigo' => 9308, 'descripcion' => 'Libano', 'activo' => true],
            ['codigo' => 9141, 'descripcion' => 'Liberia', 'activo' => true],
            ['codigo' => 9116, 'descripcion' => 'Libia', 'activo' => true],
            ['codigo' => 9419, 'descripcion' => 'Liechtenstein, Principado De', 'activo' => true],
            ['codigo' => 9440, 'descripcion' => 'Lituania', 'activo' => true],
            ['codigo' => 9420, 'descripcion' => 'Luxemburgo, Gran Ducado De', 'activo' => true],
            ['codigo' => 9437, 'descripcion' => 'Macedonia', 'activo' => true],
            ['codigo' => 9119, 'descripcion' => 'Madagascar', 'activo' => true],
            ['codigo' => 9330, 'descripcion' => 'Malasia', 'activo' => true],
            ['codigo' => 9421, 'descripcion' => 'Malta', 'activo' => true],
            ['codigo' => 9105, 'descripcion' => 'Marruecos', 'activo' => true],
            ['codigo' => 9129, 'descripcion' => 'Mauricio', 'activo' => true],
            ['codigo' => 9219, 'descripcion' => 'Mexico', 'activo' => true],
            ['codigo' => 9506, 'descripcion' => 'Micronesia', 'activo' => true],
            ['codigo' => 9432, 'descripcion' => 'Moldavia', 'activo' => true],
            ['codigo' => 9422, 'descripcion' => 'Monaco, Principado De', 'activo' => true],
            ['codigo' => 9317, 'descripcion' => 'Mongolia', 'activo' => true],
            ['codigo' => 9452, 'descripcion' => 'Montenegro', 'activo' => true],
            ['codigo' => 9117, 'descripcion' => 'Mozambique', 'activo' => true],
            ['codigo' => 9132, 'descripcion' => 'Namibia', 'activo' => true],
            ['codigo' => 9336, 'descripcion' => 'Nepal', 'activo' => true],
            ['codigo' => 9220, 'descripcion' => 'Nicaragua', 'activo' => true],
            ['codigo' => 9111, 'descripcion' => 'Nigeria', 'activo' => true],
            ['codigo' => 9423, 'descripcion' => 'Noruega', 'activo' => true],
            ['codigo' => 9502, 'descripcion' => 'Nueva Zelanda', 'activo' => true],
            ['codigo' => 9339, 'descripcion' => 'Oman', 'activo' => true],
            ['codigo' => 9414, 'descripcion' => 'Paises Bajos', 'activo' => true],
            ['codigo' => 9318, 'descripcion' => 'Pakistan', 'activo' => true],
            ['codigo' => 9505, 'descripcion' => 'Palau', 'activo' => true],
            ['codigo' => 9314, 'descripcion' => 'Palestina', 'activo' => true],
            ['codigo' => 9221, 'descripcion' => 'Panama', 'activo' => true],
            ['codigo' => 9503, 'descripcion' => 'Papua Nueva Guinea', 'activo' => true],
            ['codigo' => 9222, 'descripcion' => 'Paraguay', 'activo' => true],
            ['codigo' => 9233, 'descripcion' => 'Peru', 'activo' => true],
            ['codigo' => 9424, 'descripcion' => 'Polonia', 'activo' => true],
            ['codigo' => 9425, 'descripcion' => 'Portugal', 'activo' => true],
            ['codigo' => 9223, 'descripcion' => 'Puerto Rico', 'activo' => true],
            ['codigo' => 9450, 'descripcion' => 'R. Unido de G. Bretana e Irlanda del Nte.', 'activo' => true],
            ['codigo' => 9412, 'descripcion' => 'Reino Unido', 'activo' => true],
            ['codigo' => 9143, 'descripcion' => 'Rep. Democratica De Santo Tome Y Principe', 'activo' => true],
            ['codigo' => 9124, 'descripcion' => 'Rep. Democratica Del Congo', 'activo' => true],
            ['codigo' => 9103, 'descripcion' => 'Republica Arabe De Egipto', 'activo' => true],
            ['codigo' => 9406, 'descripcion' => 'Republica Checa', 'activo' => true],
            ['codigo' => 9346, 'descripcion' => 'Republica De Armenia', 'activo' => true],
            ['codigo' => 9125, 'descripcion' => 'Republica De Burundi', 'activo' => true],
            ['codigo' => 9136, 'descripcion' => 'Republica De Cabo Verde', 'activo' => true],
            ['codigo' => 9301, 'descripcion' => 'Republica de Corea del Sur', 'activo' => true],
            ['codigo' => 9508, 'descripcion' => 'Republica De Fiyi', 'activo' => true],
            ['codigo' => 9134, 'descripcion' => 'Republica De Gambia', 'activo' => true],
            ['codigo' => 9127, 'descripcion' => 'Republica De Guinea', 'activo' => true],
            ['codigo' => 9142, 'descripcion' => 'Republica De Guinea - Bisau', 'activo' => true],
            ['codigo' => 9507, 'descripcion' => 'Republica De Kiribati', 'activo' => true],
            ['codigo' => 9147, 'descripcion' => 'Republica De Las Seychelles', 'activo' => true],
            ['codigo' => 9138, 'descripcion' => 'Republica De Niger', 'activo' => true],
            ['codigo' => 9144, 'descripcion' => 'Republica De Ruanda', 'activo' => true],
            ['codigo' => 9140, 'descripcion' => 'Republica De Uganda', 'activo' => true],
            ['codigo' => 9133, 'descripcion' => 'Republica Del Congo', 'activo' => true],
            ['codigo' => 9347, 'descripcion' => 'Republica Democratica De Timor Oriental', 'activo' => true],
            ['codigo' => 9349, 'descripcion' => 'Republica Democratica Popular Lao', 'activo' => true],
            ['codigo' => 9224, 'descripcion' => 'Republica Dominicana', 'activo' => true],
            ['codigo' => 9145, 'descripcion' => 'Republica Islamica De Mauritania', 'activo' => true],
            ['codigo' => 9146, 'descripcion' => 'Republica Togolesa', 'activo' => true],
            ['codigo' => 9126, 'descripcion' => 'Republica Unida De Tanzania', 'activo' => true],
            ['codigo' => 9426, 'descripcion' => 'Rumania', 'activo' => true],
            ['codigo' => 9429, 'descripcion' => 'Rusia', 'activo' => true],
            ['codigo' => 9504, 'descripcion' => 'Samoa Americana', 'activo' => true],
            ['codigo' => 9239, 'descripcion' => 'San Cristobal Y Nieves', 'activo' => true],
            ['codigo' => 9447, 'descripcion' => 'San Marino, Republica De', 'activo' => true],
            ['codigo' => 9242, 'descripcion' => 'San Vicente Y Las Granadinas', 'activo' => true],
            ['codigo' => 9235, 'descripcion' => 'Santa Lucia', 'activo' => true],
            ['codigo' => 9121, 'descripcion' => 'Senegal', 'activo' => true],
            ['codigo' => 9448, 'descripcion' => 'Serbia', 'activo' => true],
            ['codigo' => 9135, 'descripcion' => 'Sierra Leona', 'activo' => true],
            ['codigo' => 9325, 'descripcion' => 'Singapur', 'activo' => true],
            ['codigo' => 9312, 'descripcion' => 'Siria', 'activo' => true],
            ['codigo' => 9110, 'descripcion' => 'Somalia', 'activo' => true],
            ['codigo' => 9309, 'descripcion' => 'Sri Lanka', 'activo' => true],
            ['codigo' => 9106, 'descripcion' => 'Sudafrica', 'activo' => true],
            ['codigo' => 9128, 'descripcion' => 'Sudan', 'activo' => true],
            ['codigo' => 9427, 'descripcion' => 'Suecia', 'activo' => true],
            ['codigo' => 9428, 'descripcion' => 'Suiza', 'activo' => true],
            ['codigo' => 9225, 'descripcion' => 'Surinam', 'activo' => true],
            ['codigo' => 9118, 'descripcion' => 'Swazilandia', 'activo' => true],
            ['codigo' => 9310, 'descripcion' => 'Tailandia', 'activo' => true],
            ['codigo' => 9323, 'descripcion' => 'Taiwan', 'activo' => true],
            ['codigo' => 9342, 'descripcion' => 'Tayikistan', 'activo' => true],
            ['codigo' => 9226, 'descripcion' => 'Trinidad Y Tobago', 'activo' => true],
            ['codigo' => 9109, 'descripcion' => 'Tunez', 'activo' => true],
            ['codigo' => 9329, 'descripcion' => 'Turkmenistan', 'activo' => true],
            ['codigo' => 9315, 'descripcion' => 'Turquia', 'activo' => true],
            ['codigo' => 9434, 'descripcion' => 'Ucrania', 'activo' => true],
            ['codigo' => 9139, 'descripcion' => 'Union De Las Comoras', 'activo' => true],
            ['codigo' => 9227, 'descripcion' => 'Uruguay', 'activo' => true],
            ['codigo' => 9343, 'descripcion' => 'Uzbekistan', 'activo' => true],
            ['codigo' => 9228, 'descripcion' => 'Venezuela', 'activo' => true],
            ['codigo' => 9320, 'descripcion' => 'Vietnam', 'activo' => true],
            ['codigo' => 9322, 'descripcion' => 'Yemen', 'activo' => true],
            ['codigo' => 9430, 'descripcion' => 'Yugoslavia', 'activo' => true],
            ['codigo' => 9115, 'descripcion' => 'Zaire', 'activo' => true],
            ['codigo' => 9107, 'descripcion' => 'Zambia', 'activo' => true],
            ['codigo' => 9108, 'descripcion' => 'Zimbabwe', 'activo' => true],
        ];

        $rows = array_map(static fn (array $row): array => $row + [
            'created_at' => $now,
            'updated_at' => $now,
        ], $rows);

        DB::table('maestro_pais')->insert($rows);
    }
}
