<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaestroProgramasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $rows = [
            [
                'codigo' => 1,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Arquitectura',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 251,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Urbanismo',
                'tipo_autorizacion' => 'Declarado por la universidad',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 3,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ciencia de la Computacion',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 10,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Fisica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 22,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Fisica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 79,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Matematica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 80,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Quimica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 11,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Ambiental',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 13,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria de Higiene y Seguridad Industrial',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 32,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Sanitaria',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 12,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Civil',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 15,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria de Petroleo y Gas Natural',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 30,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Petroquimica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 18,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Economica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 21,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Estadistica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 208,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria de Ciberseguridad',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 17,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria de Telecomunicaciones',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 19,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Electrica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 20,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Electronica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 14,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria de Minas',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 23,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Geologica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 28,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Metalurgica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 16,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria de Sistemas',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 240,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria de Software',
                'tipo_autorizacion' => 'Declarado por la universidad',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 24,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Industrial',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 297,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Aeroespacial',
                'tipo_autorizacion' => 'Declarado por la universidad',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 25,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Mecanica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 26,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Mecanica y Electrica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 27,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Mecatronica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 29,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Naval',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 31,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Quimica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 33,
                'nivel_academico' => 'Carrera Profesional',
                'programa' => 'Ingenieria Textil',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 2,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Automatizacion e Instrumentacion',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 81,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Segunda Especialidad en Ingenieria Acustica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 82,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Segunda Especializacion Profesional en Diseno Urbano',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 83,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Segunda Especializacion Profesional en Ingenieria Ambiental en Control de Vectores',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 84,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Segunda Especializacion Profesional en Ingenieria de Higiene y Seguridad Alimentaria',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 85,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Segunda Especializacion Profesional en Ingenieria de Sismorresistente',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 86,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Segunda Especializacion Profesional en Ingenieria Sanitaria -Residuos Solidos',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 87,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Segunda Especializacion Profesional en Ingenieria y Gerencia del Gas',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 88,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Segunda Especializacion Profesional en Planificacion del Desarrollo y Gestion Ambiental',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 89,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Segunda Especializacion Profesional en Procesamiento de Senales',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 90,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Segunda Especializacion Profesional en Sistemas de Potencia',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 91,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Segunda Especializacion Profesional en Telecomunicaciones',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 92,
                'nivel_academico' => 'Segunda Especialidad',
                'programa' => 'Segunda Especializacion Profesional en Telematica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 246,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria Ejecutiva en Transformacion Digital',
                'tipo_autorizacion' => 'Declarado por la universidad',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 248,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Administracion de Empresas (MBA) con mencion en Gerencia y Tecnologia',
                'tipo_autorizacion' => 'Declarado por la universidad',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 243,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Hidrogeno Verde',
                'tipo_autorizacion' => 'Declarado por la universidad',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 35,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias con Mencion en Arquitectura - Historia, Teoria y Critica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 42,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Conservacion y Gestion del Patrimonio Edificado',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 64,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Planificacion y Gestion de la Vivienda',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 65,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Planificacion y Gestion Urbano Regional',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 67,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Regeneracion Urbana',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 40,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ciencia de la Computacion',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 44,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Economia Matematica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 45,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Energia Nuclear',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 46,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Energias Renovables y Eficiencia Energetica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 47,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Fisica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 48,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Fisica Medica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 63,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Matematica Aplicada',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 247,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Modelizacion Matematica y Computacional',
                'tipo_autorizacion' => 'Declarado por la universidad',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 66,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Quimica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 245,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria de Especializacion en Ergonomia',
                'tipo_autorizacion' => 'Declarado por la universidad',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 50,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria Ambiental',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 250,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria Ambiental con mencion en Seguridad Industrial e Higiene Ocupacional',
                'tipo_autorizacion' => 'Declarado por la universidad',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 51,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria Civil',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 68,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Direccion y Administracion de la Construccion',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 70,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Gestion del Riesgo de Desastres',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 78,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Tecnologia de la Construccion',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 53,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria de Petroleo y Gas Natural',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 39,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias con Mencion en Proyectos de Inversion',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 41,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ciencias Actuariales',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 43,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Econometria Bancaria y Financiera',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 49,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Gestion Cuantitativa del Riesgo Financiero',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 57,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria Financiera',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 242,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Data Science',
                'tipo_autorizacion' => 'Declarado por la universidad',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 69,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Gerencia Publica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 55,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria Electrica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 56,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria Electronica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 52,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria de Minas',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 58,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria Geologica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 60,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria Metalurgica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 71,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Gestion Minera',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 76,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Mineria y Medio Ambiente',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 77,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Seguridad y Salud Minera',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 54,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria de Sistemas',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 59,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria Industrial',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 36,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias con Mencion en Ciencia de los Materiales',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 37,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias con Mencion en Energetica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 38,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias con Mencion en Ingenieria Mecatronica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 61,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria Naval',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 62,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria Quimica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 203,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias en Ingenieria Textil con mencion en Gestion de Empresas Textiles',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 75,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ingenieria de Procesos',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 34,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ciencias',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 72,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Gestion Tecnologica Empresarial',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 73,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ingenieria',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 74,
                'nivel_academico' => 'Maestria',
                'programa' => 'Maestria en Ingenieria Aeronautica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 4,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ciencias con Mencion en Energetica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 244,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Hidrogeno Verde',
                'tipo_autorizacion' => 'Declarado por la universidad',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 204,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ciencias en Arquitectura',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 5,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ciencias con Mencion en Fisica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 6,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ciencias con Mencion en Matematica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 7,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ciencias con Mencion en Quimica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 200,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ciencias e Ingenieria Ambientales con mencion en Abastecimiento de Agua y Saneamiento',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 199,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ciencias e Ingenieria Ambientales con mencion en Desarrollo Sostenible',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 201,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ciencias e Ingenieria Ambientales con mencion en Seguridad Industrial y Salud en el Trabajo',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 205,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ciencias e Ingenieria Civil',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 206,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ciencias e Ingenieria Economica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 207,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ciencias e Ingenieria Estadistica',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 202,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Gobierno y Politicas Publicas',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 8,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ingenieria de Sistemas',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
            [
                'codigo' => 9,
                'nivel_academico' => 'Doctorado',
                'programa' => 'Doctorado en Ingenieria Industrial',
                'tipo_autorizacion' => 'Reconocido por Lic.',
                'vigencia' => 'Vigente',
                'efi' => 'No',
                'activo' => true,
            ],
        ];

        $rows = array_map(static fn (array $row): array => $row + [
            'created_at' => $now,
            'updated_at' => $now,
        ], $rows);

        DB::table('maestro_programas')->insert($rows);
    }
}
