<?php

namespace App\Filament\Resources\Postulantes\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class PostulantesTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('codigo_sede_filial')
                    ->searchable(),
                TextColumn::make('tipo_proceso_catalogo_codigo')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('tipo_proceso')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('proceso_admision')
                    ->searchable(),
                TextColumn::make('numero_convocatoria')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('tipo_documento_catalogo_codigo')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('tipo_documento')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('nro_documento')
                    ->searchable(),
                TextColumn::make('nombres')
                    ->searchable(),
                TextColumn::make('primer_apellido')
                    ->searchable(),
                TextColumn::make('segundo_apellido')
                    ->searchable(),
                TextColumn::make('apellido_casada')
                    ->searchable(),
                TextColumn::make('solo_un_apellido_catalogo_codigo')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('solo_un_apellido')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('sexo_catalogo_codigo')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('sexo')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('fecha_nacimiento')
                    ->date()
                    ->sortable(),
                TextColumn::make('pais_nacimiento')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('nacionalidad')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('ubigeo_nacimiento')
                    ->searchable(),
                TextColumn::make('ubigeo_domicilio')
                    ->searchable(),
                TextColumn::make('condicion_discapacidad_catalogo_codigo')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('condicion_discapacidad')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('tipo_discapacidad_catalogo_codigo')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('tipo_discapacidad')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('celular')
                    ->searchable(),
                TextColumn::make('correo_personal')
                    ->searchable(),
                TextColumn::make('codigo_facultad_unidad_opcion_1')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('codigo_facultad_unidad_opcion_2')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('codigo_facultad_unidad_opcion_3')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('codigo_programa_opcion_1')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('codigo_programa_opcion_2')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('codigo_programa_opcion_3')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('fecha_postulacion')
                    ->date()
                    ->sortable(),
                TextColumn::make('puntaje_obtenido')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('modalidad_admision_catalogo_codigo')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('modalidad_admision')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('modalidad_estudio_catalogo_codigo')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('modalidad_estudio')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('es_ingresante')
                    ->searchable(),
                TextColumn::make('codigo_facultad_unidad_ingreso')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('codigo_programa_ingreso')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('fecha_ingreso')
                    ->date()
                    ->sortable(),
                TextColumn::make('correo_institucional')
                    ->searchable(),
                TextColumn::make('codigo_orcid')
                    ->searchable(),
                TextColumn::make('pertenencia_codigo_categoria')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('pertenencia_costumbres_antepasados')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('pueblo_indigena_codigo_categoria')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('pueblo_indigena_originario')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('habla_lengua_codigo_categoria')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('habla_lengua_indigena')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('lengua_indigena_codigo_categoria')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('lengua_indigena_originaria')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('nombres_materno')
                    ->searchable(),
                TextColumn::make('primer_apellido_materno')
                    ->searchable(),
                TextColumn::make('segundo_apellido_materno')
                    ->searchable(),
                TextColumn::make('apellido_casada_materno')
                    ->searchable(),
                TextColumn::make('nombres_paterno')
                    ->searchable(),
                TextColumn::make('primer_apellido_paterno')
                    ->searchable(),
                TextColumn::make('segundo_apellido_paterno')
                    ->searchable(),
                TextColumn::make('maestro_proceso_admision_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
