<?php

namespace App\Filament\Resources\Postulantes\Schemas;

use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Schema;

class PostulanteForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('codigo_sede_filial')
                    ->required(),
                TextInput::make('tipo_proceso_catalogo_codigo')
                    ->required()
                    ->numeric(),
                TextInput::make('tipo_proceso')
                    ->required()
                    ->numeric(),
                TextInput::make('proceso_admision')
                    ->required(),
                TextInput::make('numero_convocatoria')
                    ->required()
                    ->numeric(),
                TextInput::make('tipo_documento_catalogo_codigo')
                    ->required()
                    ->numeric(),
                TextInput::make('tipo_documento')
                    ->required()
                    ->numeric(),
                TextInput::make('nro_documento')
                    ->required(),
                TextInput::make('nombres')
                    ->required(),
                TextInput::make('primer_apellido')
                    ->required(),
                TextInput::make('segundo_apellido')
                    ->required(),
                TextInput::make('apellido_casada'),
                TextInput::make('solo_un_apellido_catalogo_codigo')
                    ->required()
                    ->numeric(),
                TextInput::make('solo_un_apellido')
                    ->required()
                    ->numeric(),
                TextInput::make('sexo_catalogo_codigo')
                    ->required()
                    ->numeric(),
                TextInput::make('sexo')
                    ->required()
                    ->numeric(),
                DatePicker::make('fecha_nacimiento')
                    ->required(),
                TextInput::make('pais_nacimiento')
                    ->required()
                    ->numeric(),
                TextInput::make('nacionalidad')
                    ->required()
                    ->numeric(),
                TextInput::make('ubigeo_nacimiento'),
                TextInput::make('ubigeo_domicilio'),
                TextInput::make('condicion_discapacidad_catalogo_codigo')
                    ->numeric(),
                TextInput::make('condicion_discapacidad')
                    ->numeric(),
                TextInput::make('tipo_discapacidad_catalogo_codigo')
                    ->numeric(),
                TextInput::make('tipo_discapacidad')
                    ->numeric(),
                TextInput::make('celular')
                    ->required(),
                TextInput::make('correo_personal')
                    ->required(),
                TextInput::make('codigo_facultad_unidad_opcion_1')
                    ->required()
                    ->numeric(),
                TextInput::make('codigo_facultad_unidad_opcion_2')
                    ->numeric(),
                TextInput::make('codigo_facultad_unidad_opcion_3')
                    ->numeric(),
                TextInput::make('codigo_programa_opcion_1')
                    ->required()
                    ->numeric(),
                TextInput::make('codigo_programa_opcion_2')
                    ->numeric(),
                TextInput::make('codigo_programa_opcion_3')
                    ->numeric(),
                DatePicker::make('fecha_postulacion')
                    ->required(),
                TextInput::make('puntaje_obtenido')
                    ->required()
                    ->numeric(),
                TextInput::make('modalidad_admision_catalogo_codigo')
                    ->required()
                    ->numeric(),
                TextInput::make('modalidad_admision')
                    ->required()
                    ->numeric(),
                TextInput::make('modalidad_estudio_catalogo_codigo')
                    ->required()
                    ->numeric(),
                TextInput::make('modalidad_estudio')
                    ->required()
                    ->numeric(),
                TextInput::make('es_ingresante')
                    ->required(),
                TextInput::make('codigo_facultad_unidad_ingreso')
                    ->numeric(),
                TextInput::make('codigo_programa_ingreso')
                    ->numeric(),
                DatePicker::make('fecha_ingreso'),
                TextInput::make('correo_institucional'),
                TextInput::make('codigo_orcid'),
                TextInput::make('pertenencia_codigo_categoria')
                    ->numeric(),
                TextInput::make('pertenencia_costumbres_antepasados')
                    ->numeric(),
                TextInput::make('pueblo_indigena_codigo_categoria')
                    ->numeric(),
                TextInput::make('pueblo_indigena_originario')
                    ->numeric(),
                TextInput::make('habla_lengua_codigo_categoria')
                    ->numeric(),
                TextInput::make('habla_lengua_indigena')
                    ->numeric(),
                TextInput::make('lengua_indigena_codigo_categoria')
                    ->numeric(),
                TextInput::make('lengua_indigena_originaria')
                    ->numeric(),
                TextInput::make('nombres_materno')
                    ->required(),
                TextInput::make('primer_apellido_materno')
                    ->required(),
                TextInput::make('segundo_apellido_materno')
                    ->required(),
                TextInput::make('apellido_casada_materno'),
                TextInput::make('nombres_paterno')
                    ->required(),
                TextInput::make('primer_apellido_paterno')
                    ->required(),
                TextInput::make('segundo_apellido_paterno')
                    ->required(),
                TextInput::make('maestro_proceso_admision_id')
                    ->required()
                    ->numeric(),
            ]);
    }
}
